# ICET Point Cloud Registration Demo

In [11]:
from vedo import *
import os
from ipyvtklink.viewer import ViewInteractiveWidget
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.math import sin, cos, tan
import tensorflow_probability as tfp

# #Force run on CPU (uncomment for hardware debugging) ~~~~~~~~~~~~~~~~~~~~~~~
# # print(tf.__version__)
# # Set CPU as available physical device
# my_devices = tf.config.experimental.list_physical_devices(device_type='CPU')
# tf.config.experimental.set_visible_devices(devices= my_devices, device_type='CPU')
# tf.config.set_visible_devices([], 'GPU')
# # To find out which devices your operations and tensors are assigned to
# tf.debugging.set_log_device_placement(True)
# # Create some tensors and perform an operation
# a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
# b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
# c = tf.matmul(a, b)
# # gpus = tf.config.experimental.list_physical_devices('GPU')
# # print(gpus)
# # print(tf.config.get_visible_devices()[0].device_type)
# #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

from ICET_spherical import ICET
from utils import R_tf
%load_ext autoreload
%autoreload 2
%autosave 180
%matplotlib notebook

Autosaving every 180 seconds


In [14]:
c1 = np.load("point_clouds/sample_pc_1.npy")            # keyframe scan
c2 = np.load("point_clouds/sample_pc_2.npy")            # new scan
fidelity = 50                                           # number of azimuthal bins to make square cross-section voxels 
num_iterations = 5                                      # number of iterations to run algorithm
is_draw = True                                          # visualize simulation
initial_guess = tf.constant([0., 0., 0., 0., 0., 0.])   # initial guess for transform between clouds
is_remove_moving = True                                 # remove moving objects from the frame 
is_DNN = False                                          # suppress voxels with high perspective shift using DNN

it = ICET(cloud1 = c1, cloud2 = c2, fid = fidelity, niter = num_iterations, 
           draw = is_draw, RM = is_remove_moving, DNN_filter = is_DNN, x0 = initial_guess)
ViewInteractiveWidget(it.plt.window) #comment out if <is_daraw == False>


 estimated solution vector X: 
 tf.Tensor(
[ 5.84295154e-01 -1.78336240e-02  1.45883765e-02  1.78093952e-03
 -4.72715212e-04  5.07070310e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.5546894e-01  8.6153522e-03  1.5301341e-02  1.8563502e-03
 -5.1809853e-04  2.3613870e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6238201e-01  8.0269575e-03  1.5534875e-02  1.8833835e-03
 -5.0561124e-04 -2.2308371e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6284287e-01  7.8635626e-03  1.5575391e-02  1.8776538e-03
 -4.9813173e-04 -2.5881195e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6370761e-01  7.9847397e-03  1.5606427e-02  1.8739626e-03
 -4.9319415e-04 -3.1446415e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.19253318e-03 5.82777371e-04 7.93013096e-05 1.71638076e-05
 1.10610445e-05 8.47276315e-05], shape=(6,), dty

ViewInteractiveWidget(height=1043, layout=Layout(height='auto', width='100%'), width=1280)

In [13]:
print("\n Estimated Solution Vector: \n", it.X.numpy())
print("\n Predicted Solution Error Covariance: \n", it.pred_stds.numpy())


 Estimated Solution Vector: 
 [ 6.6819602e-01  9.5334239e-03  1.5260901e-02  1.9900922e-03
 -5.6447712e-04 -6.1552221e-04]

 Predicted Solution Error Covariance: 
 [1.1785920e-03 5.5214664e-04 7.7481214e-05 1.7047119e-05 1.0648150e-05
 8.3485087e-05]
