# ICET Point Cloud Registration Demo

In [5]:
from vedo import *
import os
from ipyvtklink.viewer import ViewInteractiveWidget
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.math import sin, cos, tan
import tensorflow_probability as tfp
from ICET_spherical import ICET
from utils import R_tf

In [6]:
c1 = np.load("point_clouds/sample_pc_1.npy")            # keyframe scan
c2 = np.load("point_clouds/sample_pc_2.npy")            # new scan
fidelity = 50                                           # number of azimuthal bins to make square cross-section voxels 
num_iterations = 5                                      # number of iterations to run algorithm
is_draw = True                                          # visualize simulation
initial_guess = tf.constant([0., 0., 0., 0., 0., 0.])   # initial guess for transform between clouds
is_remove_moving = True                                 # remove moving objects from the frame 
is_DNN = False                                          # suppress voxels with high perspective shift using DNN

it = ICET(cloud1 = c1, cloud2 = c2, fid = fidelity, niter = num_iterations, 
           draw = is_draw, RM = is_remove_moving, DNN_filter = is_DNN, x0 = initial_guess)
ViewInteractiveWidget(it.plt.window)


 estimated solution vector X: 
 tf.Tensor(
[ 6.3090062e-01 -2.8014574e-03  1.5382480e-02  1.8306474e-03
 -5.2894524e-04  1.7098328e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6182196e-01  8.3185816e-03  1.5893659e-02  1.9094041e-03
 -4.5514858e-04 -2.2781943e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6433531e-01  7.8299334e-03  1.5977370e-02  1.8801364e-03
 -4.4296469e-04 -3.8632291e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6427845e-01  7.6574725e-03  1.6004309e-02  1.8768865e-03
 -4.3774507e-04 -3.8317425e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6453832e-01  7.7511640e-03  1.6129874e-02  1.8599983e-03
 -4.2092288e-04 -4.0438026e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1986912e-03 5.5283913e-04 8.1180318e-05 1.8004632e-05 1.1171236e-05
 8.5089960e-05], shape=(6,), dtype=float32)


ViewInteractiveWidget(height=1376, layout=Layout(height='auto', width='100%'), width=2488)

In [7]:
print("\n Estimated Solution Vector: \n", it.X.numpy())
print("\n Predicted Solution Error Covariance: \n", it.pred_stds.numpy())


 Estimated Solution Vector: 
 [ 6.6453832e-01  7.7511640e-03  1.6129874e-02  1.8599983e-03
 -4.2092288e-04 -4.0438026e-04]

 Predicted Solution Error Covariance: 
 [1.1986912e-03 5.5283913e-04 8.1180318e-05 1.8004632e-05 1.1171236e-05
 8.5089960e-05]
