# ICET Point Cloud Registration Demo

In [4]:
from vedo import *
import os
from ipyvtklink.viewer import ViewInteractiveWidget
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.math import sin, cos, tan
import tensorflow_probability as tfp

# #Force run on CPU (for hardware debugging) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# # print(tf.__version__)
# # Set CPU as available physical device
# my_devices = tf.config.experimental.list_physical_devices(device_type='CPU')
# tf.config.experimental.set_visible_devices(devices= my_devices, device_type='CPU')
# tf.config.set_visible_devices([], 'GPU')
# # To find out which devices your operations and tensors are assigned to
# # tf.debugging.set_log_device_placement(True)
# # Create some tensors and perform an operation
# a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
# b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
# c = tf.matmul(a, b)
# # gpus = tf.config.experimental.list_physical_devices('GPU')
# # print(gpus)
# # print(tf.config.get_visible_devices()[0].device_type)
# #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

from ICET_spherical import ICET
from utils import R_tf

# %load_ext autoreload
# %autoreload 2
# %autosave 180
# %matplotlib notebook

In [6]:
c1 = np.load("point_clouds/sample_pc_1.npy")            # keyframe scan
c2 = np.load("point_clouds/sample_pc_2.npy")            # new scan
fidelity = 50                                           # number of azimuthal bins to make square cross-section voxels 
num_iterations = 5                                      # number of iterations to run algorithm
is_draw = False                                          # visualize simulation
initial_guess = tf.constant([0., 0., 0., 0., 0., 0.])   # initial guess for transform between clouds
is_remove_moving = True                                 # remove moving objects from the frame 
is_DNN = False                                          # suppress voxels with high perspective shift using DNN

it = ICET(cloud1 = c1, cloud2 = c2, fid = fidelity, niter = num_iterations, 
           draw = is_draw, RM = is_remove_moving, DNN_filter = is_DNN, x0 = initial_guess)
# ViewInteractiveWidget(it.plt.window) #comment out if <is_daraw == False>


 estimated solution vector X: 
 tf.Tensor(
[ 5.8396858e-01 -1.7539283e-02  1.4167314e-02  1.8696527e-03
 -4.9432635e-04  5.0333324e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.56681180e-01  9.22975689e-03  1.52130835e-02  1.90319540e-03
 -5.10884624e-04  1.14050228e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6320354e-01  8.2900412e-03  1.5431124e-02  1.9192157e-03
 -4.9853447e-04 -3.0447060e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6360599e-01  8.1320982e-03  1.5468463e-02  1.9146118e-03
 -4.9294584e-04 -3.3418494e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6471869e-01  8.3980076e-03  1.5519771e-02  1.9068536e-03
 -4.8783357e-04 -4.0807063e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1886363e-03 5.6093797e-04 7.7854878e-05 1.6857955e-05 1.0963262e-05
 8.4228996e-05], shape=(6,), dtype=flo

In [7]:
print("\n Estimated Solution Vector: \n", it.X.numpy())
print("\n Predicted Solution Error Covariance: \n", it.pred_stds.numpy())


 Estimated Solution Vector: 
 [ 6.6471869e-01  8.3980076e-03  1.5519771e-02  1.9068536e-03
 -4.8783357e-04 -4.0807063e-04]

 Predicted Solution Error Covariance: 
 [1.1886363e-03 5.6093797e-04 7.7854878e-05 1.6857955e-05 1.0963262e-05
 8.4228996e-05]


In [9]:
#debug:run a bunch of times  to see if we encounter indexing bug -- yes we do!

for i in range(100):
    it = ICET(cloud1 = c1, cloud2 = c2, fid = fidelity, niter = num_iterations, 
               draw = is_draw, RM = is_remove_moving, DNN_filter = is_DNN, x0 = initial_guess)


 estimated solution vector X: 
 tf.Tensor(
[ 5.8559483e-01 -1.6717151e-02  1.4309904e-02  1.8124934e-03
 -4.9275276e-04  4.9379580e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.5754616e-01  9.5476527e-03  1.5365383e-02  1.8853638e-03
 -4.9161486e-04  4.5265071e-05], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.64153814e-01  8.85196961e-03  1.55625455e-02  1.90555037e-03
 -4.80087678e-04 -3.81705991e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6461450e-01  8.7098442e-03  1.5573022e-02  1.9023787e-03
 -4.7884852e-04 -4.1340239e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6598046e-01  8.9971730e-03  1.5639164e-02  1.8944241e-03
 -4.7348137e-04 -5.0609396e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1864231e-03 5.7050970e-04 7.7632576e-05 1.7018812e-05 1.0852245e-05
 8.4320076e-05], shape=(6,), dtype=flo


 estimated solution vector X: 
 tf.Tensor(
[ 6.6322386e-01  7.8717843e-03  1.5644915e-02  1.8868737e-03
 -4.6118803e-04 -3.1603553e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6422522e-01  8.1533855e-03  1.5715098e-02  1.8778449e-03
 -4.5347388e-04 -3.8424516e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1585862e-03 5.4627587e-04 7.8012592e-05 1.7103530e-05 1.0833815e-05
 8.1735787e-05], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 5.8220947e-01 -1.8168863e-02  1.4528870e-02  1.7386422e-03
 -4.6160794e-04  5.1635271e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.5409636e-01  8.3414428e-03  1.5414183e-02  1.8393353e-03
 -4.9047021e-04  2.7635321e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6143388e-01  7.7449791e-03  1.5574106e-02  1.8620658e-03
 -4.9477635e-04 -1.7891586e-04], shape=(6,), dtype=float32)



 estimated solution vector X: 
 tf.Tensor(
[ 5.8381087e-01 -1.8633932e-02  1.4185014e-02  1.8438231e-03
 -5.2098249e-04  5.0820275e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6031092e-01  1.0906864e-02  1.4888274e-02  1.9571041e-03
 -5.9962587e-04 -1.1793384e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6470337e-01  9.0027004e-03  1.5499590e-02  1.9220038e-03
 -5.2365620e-04 -4.1183532e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6505742e-01  8.8997092e-03  1.5466644e-02  1.9211019e-03
 -5.2069809e-04 -4.3800840e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6598099e-01  9.1082742e-03  1.5548555e-02  1.9091398e-03
 -5.1088561e-04 -5.0048612e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1794566e-03 5.6699995e-04 7.7875244e-05 1.6961398e-05 1.0972778e-05
 8.3708386e-05], shape=(6,), dtype=float32)



 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6514516e-01  8.5268747e-03  1.5625853e-02  1.8936967e-03
 -4.8197334e-04 -4.3116775e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1858480e-03 5.5910920e-04 7.8872719e-05 1.7158340e-05 1.0994415e-05
 8.3791543e-05], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 5.8515352e-01 -1.5540590e-02  1.3982689e-02  1.8770481e-03
 -5.0372398e-04  4.9806517e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.5779662e-01  9.6760755e-03  1.5083968e-02  1.9290122e-03
 -5.3736672e-04  5.2414369e-05], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6411471e-01  8.5590761e-03  1.5373888e-02  1.9342140e-03
 -5.1724730e-04 -3.4567169e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6464347e-01  8.4549868e-03  1.5380143e-02  1.9306901e-03
 -5.1521044e-04 -3.8315356e-04], shape=(6,), dtype=float32)



 estimated solution vector X: 
 tf.Tensor(
[ 5.7691127e-01 -1.8416490e-02  1.4130540e-02  1.8425331e-03
 -4.7930153e-04  5.5133156e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.5530682e-01  9.3651600e-03  1.5219096e-02  1.8789996e-03
 -5.0397334e-04  1.5969528e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6312355e-01  8.6834915e-03  1.5421742e-02  1.9043054e-03
 -5.0463894e-04 -3.2531942e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6366869e-01  8.5019870e-03  1.5456383e-02  1.8998374e-03
 -5.0087756e-04 -3.6258923e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6480452e-01  8.8218292e-03  1.5538271e-02  1.8887719e-03
 -4.9181079e-04 -4.4173488e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1794632e-03 5.8516103e-04 7.7915174e-05 1.6951708e-05 1.0991658e-05
 8.3935796e-05], shape=(6,), dtype=float32)



 estimated solution vector X: 
 tf.Tensor(
[ 6.6425669e-01  8.4414668e-03  1.5426117e-02  1.9361535e-03
 -5.0519808e-04 -3.8037487e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6556388e-01  8.8337921e-03  1.5487156e-02  1.9280961e-03
 -4.9943989e-04 -4.7081808e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1914691e-03 5.6745124e-04 7.6895056e-05 1.6798445e-05 1.0779598e-05
 8.4502411e-05], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 5.8261490e-01 -1.8052595e-02  1.4229463e-02  1.8624023e-03
 -4.9975270e-04  5.0395224e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.5650779e-01  9.3806852e-03  1.5365843e-02  1.8853553e-03
 -4.9610471e-04  8.8902190e-05], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6288126e-01  8.3896276e-03  1.5580261e-02  1.8972944e-03
 -4.8798861e-04 -3.0978388e-04], shape=(6,), dtype=float32)



 estimated solution vector X: 
 tf.Tensor(
[ 5.7918680e-01 -1.8589333e-02  1.4389453e-02  1.8128805e-03
 -4.9766566e-04  5.3786347e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.5661103e-01  9.5134825e-03  1.5341034e-02  1.8789429e-03
 -5.0627370e-04  9.8051503e-05], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6316760e-01  8.3572119e-03  1.5586145e-02  1.8820623e-03
 -4.8732606e-04 -3.0434632e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6363746e-01  8.2163112e-03  1.5585633e-02  1.8799159e-03
 -4.8559674e-04 -3.3603969e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6461056e-01  8.4370514e-03  1.5677404e-02  1.8666568e-03
 -4.7507341e-04 -4.0084374e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1777336e-03 5.6517718e-04 7.8272038e-05 1.6957363e-05 1.0990805e-05
 8.3335573e-05], shape=(6,), dtype=float32)



 estimated solution vector X: 
 tf.Tensor(
[ 6.6373199e-01  8.1023090e-03  1.5577216e-02  1.9140888e-03
 -4.8673936e-04 -3.4080719e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6463959e-01  8.3180461e-03  1.5635855e-02  1.9047568e-03
 -4.8031032e-04 -4.0089383e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1613313e-03 5.5352511e-04 7.7988705e-05 1.7071550e-05 1.0940835e-05
 8.2134648e-05], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 5.8074683e-01 -1.8932020e-02  1.4146389e-02  1.7958102e-03
 -5.0778396e-04  5.2841580e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.5551835e-01  9.1329943e-03  1.5286354e-02  1.8794965e-03
 -5.0433731e-04  1.9794656e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6208184e-01  7.9695517e-03  1.5567646e-02  1.8982304e-03
 -4.8534496e-04 -2.1310450e-04], shape=(6,), dtype=float32)



 estimated solution vector X: 
 tf.Tensor(
[ 5.8612394e-01 -1.6276348e-02  1.4331808e-02  1.8881126e-03
 -5.0532183e-04  4.9379850e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.5575296e-01  8.5133724e-03  1.5425369e-02  1.8668140e-03
 -4.9070886e-04  2.0165136e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6213810e-01  7.6926770e-03  1.5557279e-02  1.8810190e-03
 -4.8264669e-04 -2.0946586e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6269284e-01  7.5953985e-03  1.5556286e-02  1.8800598e-03
 -4.8331765e-04 -2.4816827e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6391444e-01  7.9642236e-03  1.5616031e-02  1.8718087e-03
 -4.7810713e-04 -3.3244805e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1752833e-03 5.5467564e-04 7.8164107e-05 1.6885364e-05 1.0877060e-05
 8.3132974e-05], shape=(6,), dtype=float32)



 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6310650e-01  7.8917490e-03  1.5627217e-02  1.8777383e-03
 -4.7706882e-04 -2.6258142e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1497831e-03 5.6002033e-04 7.8735371e-05 1.7148428e-05 1.1073637e-05
 8.0822392e-05], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 5.8357108e-01 -1.8243708e-02  1.4127447e-02  1.8473123e-03
 -5.2749348e-04  5.1376200e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.5743315e-01  9.5904637e-03  1.5029494e-02  1.9052729e-03
 -5.5468292e-04  9.4675925e-05], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6389740e-01  8.4820269e-03  1.5364152e-02  1.9110003e-03
 -5.2443572e-04 -3.2428931e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6449314e-01  8.4043359e-03  1.5359230e-02  1.9123072e-03
 -5.2286597e-04 -3.6695821e-04], shape=(6,), dtype=float32)



 estimated solution vector X: 
 tf.Tensor(
[ 5.9104443e-01 -1.4486641e-02  1.3938038e-02  1.8467944e-03
 -5.5206381e-04  4.5303763e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.5842968e-01  9.9333562e-03  1.5160913e-02  1.9089896e-03
 -5.3125259e-04 -1.6819220e-05], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6408700e-01  8.8005569e-03  1.5371502e-02  1.9370429e-03
 -5.1989884e-04 -3.7860346e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.6452903e-01  8.6922757e-03  1.5374142e-02  1.9361965e-03
 -5.1822886e-04 -4.0982023e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6554630e-01  8.9365114e-03  1.5447498e-02  1.9261668e-03
 -5.1027897e-04 -4.7786627e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.17708929e-03 5.67680167e-04 7.72751082e-05 1.67849557e-05
 1.09180455e-05 8.35926767e-05], shape=(6,), dtype=flo


 estimated solution vector X: 
 tf.Tensor(
[ 6.6394752e-01  8.5727321e-03  1.5558479e-02  1.9062408e-03
 -4.9284071e-04 -3.2629687e-04], shape=(6,), dtype=float32)

 ---checking for moving objects---

 estimated solution vector X: 
 tf.Tensor(
[ 6.6573864e-01  9.2372885e-03  1.5631814e-02  1.9291346e-03
 -4.8247300e-04 -4.5312420e-04], shape=(6,), dtype=float32)
pred_stds: 
 tf.Tensor(
[1.1840573e-03 5.8370706e-04 7.7973920e-05 1.7384473e-05 1.0817874e-05
 8.3906962e-05], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 5.87534904e-01 -1.66636463e-02  1.40938945e-02  1.84712466e-03
 -4.94638691e-04  4.72608116e-03], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.5615588e-01  8.7499153e-03  1.5145105e-02  1.9051969e-03
 -5.2231632e-04  1.2714369e-04], shape=(6,), dtype=float32)

 estimated solution vector X: 
 tf.Tensor(
[ 6.61551714e-01  7.54470564e-03  1.54267745e-02  1.90281728e-03
 -5.07764868e-04 -2.03561096e-04], shape=(6,), dty